### PR TITLE
[2371] Use cursor.lastrowid instead of SELECT query for SQLite/MySQL.

### PR DESCRIPTION
**Pull request by alibotean**
## Problem

Both `SQLite` and `MySQL` Python DB-APIs provide last insert row ID value using a cursor property thus making a second query not required.
## Changes

Instead of using a SELECT statement to retrieve the last inserted row ID both SQLite/MySQL configurations were changed to use `cursor.lastrowid`.
## How to test

reviewers @adiroiban 

Please check that the code changes make sense. Thanks!

PS: I've already prepared two system tests for server (SQLite/MySQL) to check that the saved entry ID's is updated accordingly.

### CODE REVIEW

**Comment by alibotean** [comment]
needs-review

**Comment by adiroiban** [comment]
Changes looks good. Is there ok interface... or some high level class where to define this new method os not implemented.. so that when a new DB is supported the developers will know that he/she also needs to implement this.

Regarding test, can you write them as twistart tests?

If the code is ok maybe we can send it upstream

thanks!

approved-at 2cf6a81

**Comment by alibotean** [comment]
> Changes looks good. Is there ok interface... or some high level class where to define this new method os not implemented.. so that when a new DB is supported the developers will know that he/she also needs to implement this.

Twistar provides a default implementation for all databases, namely the SELECT query.

There is no need to override/implement the `getLastInsertRowID` method unless you want to provide a different implementation.

**Comment by alibotean** [comment]
> Regarding test, can you write them as twistart tests? If the code is ok maybe we can send it upstream

Just took a glance at the tests :smile:. The db backend is hardcoded to `sqlite3` and there are already tests for save which check that id is a number.

I will try to run them.

**Comment by alibotean** [comment]
> I will try to run them.

All of the tests are failing on my machine without much info on how to fix this.

**Pull request merged**
